source 'http://rubygems.org'

gem 'rails', '~>3.2.0'

gem 'sqlite3'

gem 'uglifier'
gem 'execjs'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :test do
  gem 'capybara', '~>1'
  gem 'database_cleaner'
  gem 'cucumber-rails', :require => false
  gem 'cucumber'
  gem 'rspec-rails'
end
