module Netzke
  module Rails
    module ActionViewExt
      # Implementation of Touch-specific helpers
      module Touch #:nodoc:

        protected

          def netzke_touch_css_include(theme)
            # theme is not used for now

            res = stylesheet_link_tag("/sencha-touch/resources/css/sencha-touch")

            # Netzke-related (dynamically generated by NetzkeController)
            res << "\n" << stylesheet_link_tag("/netzke/touch")

            res
          end

          def netzke_touch_js
            res = []
            res << content_for(:netzke_js_classes)
            res << "\n"

            res << "Ext.setup({"
              res << "onReady: function(){"
              res << content_for(:netzke_on_ready)
              res << "}"
            res << "});"

            javascript_tag res.join("\n")
          end


          def netzke_touch_js_include
            res = []

            # ExtJS
            res << (ENV['RAILS_ENV'] == 'development' ? javascript_include_tag("/sencha-touch/sencha-touch-debug.js") : javascript_include_tag("/sencha-touch/sencha-touch"))

            # Netzke (dynamically generated)
            res << javascript_include_tag("/netzke/touch")

            res.join("\n")
          end

      end
    end
  end
end
